serverID: server
database:
  type: 'SQLite'
  connection:
    host: 'localhost'
    port: 3306
    database: 'HuskTowns'
    username: 'root'
    password: 'pa55w0rd'
    params: '?autoReconnect=true&useSSL=false'
  table_names:
    player_table: 'husktowns_players'
    towns_table: 'husktowns_towns'
    claims_table: 'husktowns_claims'
    locations_table: 'husktowns_locations'
level_limits:
  1:
    cost: 0
    claims: 10
    members: 8
    crop_boost: 0
    spawner_boost: 0
  2:
    cost: 500
    claims: 15
    members: 10
    crop_boost: 0
    spawner_boost: 0
  3:
    cost: 2500
    claims: 20
    members: 15
    crop_boost: 0
    spawner_boost: 0