#  ------------------------------
# |       HuskTowns Config       |
# |    Developed by William278   |
#  ------------------------------
# Configuration guide: IF YOU ARE SEEING THIS TEXT PLEASE MESSAGE ME ON DISCORD TO LET ME KNOW I AM
# A MASSIVE DONUT AND FORGOT TO PUT THE CONFIGURATION GUIDE LINK IN THE CONFIG FILE HEADER

language: 'en-gb'
data_storage_options:
  storage_type: 'SQLite'
  mysql_credentials:
    host: 'localhost'
    port: 3306
    database: 'HuskTowns'
    username: 'root'
    password: 'pa55w0rd'
    params: '?autoReconnect=true&useSSL=false'
  table_names:
    player_table: 'husktowns_players'
    towns_table: 'husktowns_towns'
    claims_table: 'husktowns_claims'
    locations_table: 'husktowns_locations'
bungee_options:
  enable_bungee_mode: true
  server_id: 'server'
  cluster_id: 0
level_deposit_requirements:
  - 0.0
  - 500.0
  - 2500.0
  - 5000.0
  - 10000.0
  - 15000.0
  - 30000.0
  - 50000.0
  - 75000.0
  - 100000.0
  - 200000.0
  - 300000.0
  - 400000.0
  - 500000.0
  - 750000.0
  - 1000000.0
  - 2500000.0
  - 5000000.0
  - 10000000.0
  - 50000000.0
level_max_claims:
  - 10
  - 15
  - 20
  - 25
  - 50
  - 60
  - 75
  - 80
  - 80
  - 100
  - 125
  - 150
  - 175
  - 200
  - 250
  - 300
  - 400
  - 500
  - 600
  - 700
level_max_members:
  - 8
  - 10
  - 15
  - 20
  - 25
  - 30
  - 30
  - 30
  - 30
  - 50
  - 50
  - 50
  - 50
  - 50
  - 75
  - 75
  - 75
  - 100
  - 100
  - 100