name: HuskTowns
version: ${project.version}
main: me.william278.husktowns.HuskTowns
api-version: 1.16
authors: [William278]
softdepend: [ Vault, HuskHomes, dynmap, BlueMap, Pl3xMap ]
description: ${project.description}
website: ${project.url}
libraries:
  - mysql:mysql-connector-java:8.0.25

commands:
  husktowns:
    description: View information about HuskTowns
    permission: husktowns.command.husktowns
    usage: /husktowns [help/about/status/update/reload]
  town:
    description: Create, manage & view details about towns
    usage: /town [command]
    permission: husktowns.command.town
    aliases: [ t ]
  claim:
    description: Claim the chunk you are in for your town
    usage: /claim
    permission: husktowns.command.claim
  autoclaim:
    description: Automatically claim chunks as you walk
    usage: /autoclaim
    permission: husktowns.command.claim
  unclaim:
    description: Unclaim a claimed chunk
    usage: /unclaim
    permission: husktowns.command.unclaim
    aliases: [ delclaim, abandonclaim ]
  claimlist:
    description: View a list of a town's claims
    usage: /claimlist [town] [page]
    permission: husktowns.command.claimlist
    aliases: [ claims, claimslist ]
  promote:
    description: Promote a player in your town
    usage: /promote <player>
    permission: husktowns.command.promote
    aliases: [ trust ]
  demote:
    description: Demote a player in your town
    usage: /demote <player>
    permission: husktowns.command.demote
    aliases: [ untrust ]
  map:
    description: View a map of claims
    usage: /map [x] [z] [world]
    permission: husktowns.command.map
  invite:
    description: Invite a player to join your town
    usage: /invite <player/accept/decline>
    permission: husktowns.command.invite
  evict:
    description: Kick a player from your town
    usage: /evict <player>
    permission: husktowns.command.evict
  farm:
    description: Make a claimed chunk into a town farm
    usage: /farm
    permission: husktowns.command.farm
  plot:
    description: Make or manage a plot within your town
    usage: /plot [set/remove/claim/unclaim/assign] [player]
    permission: husktowns.command.plot
  transfer:
    description: Transfer ownership of your town
    usage: /transfer <new mayor> [confirm]
    permission: husktowns.command.transfer
  admintown:
    description: Access administrator commands for towns
    usage: /admintown [command]
    permission: husktowns.administrator
    aliases: [townadmin]
  ignoreclaims:
    description: Toggle administrator claim override
    usage: /ignoreclaims
    permission: husktowns.administrator.ignore_claims
    aliases: [respectclaims]
  adminclaim:
    description: Admin-claim the chunk you are in
    usage: /adminclaim
    permission: husktowns.administrator.claim
  townlist:
    description: View an ordered list of towns
    usage: /townlist [level/name/newest/oldest]
    permission: husktowns.command.townlist
    aliases: [ townslist, towns ]
  townchat:
    description: Send a message to your town members
    usage: /townchat <message>
    permission: husktowns.command.townchat
    aliases: [tc]
  townbonus:
    description: Grant towns bonus claims or members
    usage: /townbonus <add/clear/view> <town/player>
    permission: husktowns.administrator
    aliases: [bonus]

permissions:
  husktowns.*:
    default: false
    description: Grant all HuskTowns Permissions
    children: [husktowns.administrator]
  husktowns.player:
    description: A basic pack of permissions for players
    default: false
    children:
      - husktowns.commands
      - husktowns.create_town
  husktowns.command.*:
    description: Grants access to all HuskTowns commands
    default: false
    children: [husktowns.command]
  husktowns.commands:
    description: Grants access to all HuskTowns commands
    default: false
    children:
      - husktowns.command.husktowns
      - husktowns.command.town
      - husktowns.command.claim
      - husktowns.command.unclaim
      - husktowns.command.claimlist
      - husktowns.command.promote
      - husktowns.command.demote
      - husktowns.command.map
      - husktowns.command.invite
      - husktowns.command.evict
      - husktowns.command.plot
      - husktowns.command.farm
      - husktowns.command.transfer
      - husktowns.command.townlist
  husktowns.administrator:
    description: Make admin claims, reload the plugin, check for updates
    default: op
    children:
      - husktowns.administrator.claim
      - husktowns.administrator.ignore_claims
      - husktowns.administrator.admin_claim_access
      - husktowns.bypass_teleport_warmup
      - husktowns.commands
      - husktowns.create_town
      - husktowns.town_chat_spy
  husktowns.administrator.claim:
    description: Make administrator claims
    default: op
  husktowns.administrator.ignore_claims:
    description: Toggle whether you override claim access
    default: op
  husktowns.administrator.admin_claim_access:
    description: Grants you access to building in admin claims
    default: op
  husktowns.administrator.unclaim_any:
    description: Lets you unclaim any claim in the world
    default: op
  husktowns.town_chat_spy:
    description: Spy on all town chat messages sent
    default: false
  husktowns.bypass_teleport_warmup:
    description: Lets you bypass teleportation warmup
    default: false
  husktowns.command.husktowns:
    description: Lets you use the /husktowns command
    default: true
  husktowns.command.town:
    description: Create & manage towns with /town
    default: true
    children: [husktowns.command.town.rename]
  husktowns.command.town.rename:
    description: Rename a town
    default: true
  husktowns.command.claim:
    description: Lets you claim chunks for your town
    default: true
  husktowns.command.unclaim:
    description: Lets you unclaim chunks
    default: true
  husktowns.command.claimlist:
    description: Lets you view a list of your town's claims
    default: true
  husktowns.command.promote:
    description: Lets you promote players in your town
    default: true
  husktowns.command.demote:
    description: Lets you demote players in your town
    default: true
  husktowns.command.map:
    description: Lets you view a map of nearby chunks
    default: true
  husktowns.command.invite:
    description: Lets you invite players to your town
    default: true
  husktowns.command.evict:
    description: Lets you evict players from your town
    default: true
  husktowns.command.farm:
    description: Lets you make claims into town farms
    default: true
  husktowns.command.plot:
    description: Lets you make and manage plots in your town
    default: true
  husktowns.command.transfer:
    description: Lets you transfer town ownership
    default: true
  husktowns.command.townlist:
    description: Lets you view a list of server towns
    default: true
  husktowns.create_town:
    description: Lets you make a town
    default: true
  husktowns.command.townchat:
    description: Lets you use intra-town chat
    default: true