#  ------------------------------
# |       HuskTowns Config       |
# |    Developed by William278   |
#  ------------------------------
# Configuration guide: https://github.com/WiIIiam278/HuskTowns/wiki/Config-File

language: 'en-gb'
data_storage_options:
  storage_type: 'SQLite'
  mysql_credentials:
    host: 'localhost'
    port: 3306
    database: 'HuskTowns'
    username: 'root'
    password: 'pa55w0rd'
    params: '?autoReconnect=true&useSSL=false'
  table_names:
    player_table: 'husktowns_players'
    towns_table: 'husktowns_towns'
    claims_table: 'husktowns_claims'
    locations_table: 'husktowns_locations'
    bonuses_table: 'husktowns_bonus'
    town_flags_table: 'husktowns_flags'
    plot_members_table: 'husktowns_plot_members'
bungee_options:
  enable_bungee_mode: false
  server_id: 'server'
  cluster_id: 0
general_options:
  enable_town_chat: true
  toggelable_town_chat: true
  invite_expiry: 120
  teleport_warmup_secs: 5
  teleport_warmup_sound: BLOCK_NOTE_BLOCK_BANJO
  teleport_complete_sound: ENTITY_ENDERMAN_TELEPORT
  teleport_cancel_sound: ENTITY_ITEM_BREAK
  claim_inspection_tool: 'stick'
  town_map_square_radius: 5
  admin_town_name: 'Administrators'
  admin_town_color: '#ff7e5e'
  set_town_spawn_in_first_claim: true
  allow_killing_hostiles_everywhere: true
  block_pvp_friendly_fire: true
  log_cache_loading: false
  prohibited_town_names:
    - admin
  unclaimable_worlds:
    - world_nether
    - world_the_end
  help_menu:
    hide_commands_without_permission: true
    hide_husktowns_command: false
  use_database_fallback_on_cache_fail: false
flag_options:
  default_town_flags:
    regular_chunks:
      explosion_damage: false
      fire_damage: false
      mob_griefing: false
      monster_spawning: true
      pvp: false
      public_build_access: false
      public_container_access: false
      public_interact_access: false
    farm_chunks:
      explosion_damage: true
      fire_damage: false
      mob_griefing: false
      monster_spawning: true
      pvp: false
      public_build_access: false
      public_container_access: false
      public_interact_access: false
    plot_chunks:
      explosion_damage: false
      fire_damage: false
      mob_griefing: false
      monster_spawning: true
      pvp: false
      public_build_access: false
      public_container_access: false
      public_interact_access: false
  wilderness_flags:
    explosion_damage: true
    fire_damage: true
    mob_griefing: true
    monster_spawning: true
    pvp: false
    public_build_access: true
    public_container_access: true
    public_interact_access: true
  unclaimable_world_flags:
    explosion_damage: true
    fire_damage: true
    mob_griefing: true
    monster_spawning: true
    pvp: true
    public_build_access: true
    public_container_access: true
    public_interact_access: true
  admin_claim_flags:
    explosion_damage: false
    fire_damage: false
    mob_griefing: false
    monster_spawning: false
    pvp: false
    public_build_access: false
    public_container_access: false
    public_interact_access: true
integrations:
  economy:
    enabled: true
    town_creation_cost: 150.0
    welcome_message_cost: 0.0
    farewell_message_cost: 0.0
    update_bio_cost: 0.0
    town_set_spawn_cost: 50.0
    town_rename_cost: 100.0
    make_spawn_public_cost: 25.0
    deposit_notification_threshold: 0.01
  huskhomes:
    enabled: true
    block_sethome_in_other_towns: true
  map:
    enabled: false
    plugin: 'dynmap'
    marker_set_name: 'Towns'
    use_town_colors: true
    default_town_color: '#4af7c9'
    claim_fill_opacity: 0.5
    claim_stroke_opacity: 0
    claim_stroke_weight: 1
town_levelling:
  level_deposit_requirements:
    - 0.0
    - 500.0
    - 2500.0
    - 5000.0
    - 10000.0
    - 15000.0
    - 30000.0
    - 50000.0
    - 75000.0
    - 100000.0
    - 200000.0
    - 300000.0
    - 400000.0
    - 500000.0
    - 750000.0
    - 1000000.0
    - 2500000.0
    - 5000000.0
    - 10000000.0
    - 50000000.0
  level_max_claims:
    - 10
    - 15
    - 20
    - 25
    - 50
    - 60
    - 75
    - 80
    - 80
    - 100
    - 125
    - 150
    - 175
    - 200
    - 250
    - 300
    - 400
    - 500
    - 600
    - 700
  level_max_members:
    - 8
    - 10
    - 15
    - 20
    - 25
    - 30
    - 30
    - 30
    - 30
    - 50
    - 50
    - 50
    - 50
    - 50
    - 75
    - 75
    - 75
    - 100
    - 100
    - 100
config_file_version: '1.0'