name: HuskTowns
version: '${version}'
description: 'A simple bungee-compatible Towny-style protection plugin'
website: 'https://william278.net'
main: net.william278.husktowns.HuskTowns
api-version: 1.16
author: William278
softdepend:
  - Vault
  - HuskHomes
  - dynmap
  - BlueMap
  - Squaremap
  - LuckPerms
libraries:
  - 'redis.clients:jedis:${jedis_version}'
  - 'mysql:mysql-connector-java:${mysql_driver_version}'
  - 'org.xerial:sqlite-jdbc:${sqlite_driver_version}'
  - 'org.apache.commons:commons-text:${commons_text_version}'

commands:
  husktowns:
    description: View information about HuskTowns
    permission: husktowns.command.husktowns
    usage: /husktowns [help/about/cache/update/reload]
  town:
    description: Create, manage & view details about towns
    usage: /town [command]
    permission: husktowns.command.town
    aliases: [ t ]
  claim:
    description: Claim the chunk you are in for your town
    usage: /claim
    permission: husktowns.command.claim
  autoclaim:
    description: Automatically claim chunks as you walk
    usage: /autoclaim
    permission: husktowns.command.claim
  unclaim:
    description: Unclaim a claimed chunk
    usage: /unclaim [all]
    permission: husktowns.command.unclaim
    aliases: [ delclaim, abandonclaim ]
  claimlist:
    description: View a list of a town's claims
    usage: /claimlist [town] [page]
    permission: husktowns.command.claimlist
    aliases: [ claims, claimslist ]
  promote:
    description: Promote a player in your town
    usage: /promote <player>
    permission: husktowns.command.promote
    aliases: [ trust ]
  demote:
    description: Demote a player in your town
    usage: /demote <player>
    permission: husktowns.command.demote
    aliases: [ untrust ]
  map:
    description: View a map of claims
    usage: /map [x] [z] [world]
    permission: husktowns.command.map
  invite:
    description: Invite a player to join your town
    usage: /invite <player/accept/decline>
    permission: husktowns.command.invite
  evict:
    description: Kick a player from your town
    usage: /evict <player>
    permission: husktowns.command.evict
  farm:
    description: Make a claimed chunk into a town farm
    usage: /farm
    permission: husktowns.command.farm
  plot:
    description: Make or manage a plot within your town
    usage: /plot [set/remove/claim/unclaim/assign] [player]
    permission: husktowns.command.plot
  transfer:
    description: Transfer ownership of your town
    usage: /transfer <new mayor> [confirm]
    permission: husktowns.command.transfer
  admintown:
    description: Access administrator commands for towns
    usage: /admintown [command]
    permission: husktowns.administrator
    aliases: [ townadmin ]
  ignoreclaims:
    description: Toggle administrator claim override
    usage: /ignoreclaims
    permission: husktowns.administrator.ignore_claims
    aliases: [ respectclaims ]
  adminclaim:
    description: Admin-claim the chunk you are in
    usage: /adminclaim
    permission: husktowns.administrator.claim
  townlist:
    description: View an ordered list of towns
    usage: /townlist [level/name/newest/oldest]
    permission: husktowns.command.townlist
    aliases: [ townslist, towns ]
  townchat:
    description: Send a message to your town members
    usage: /townchat <message>
    permission: husktowns.command.townchat
    aliases: [ tc ]
  townbonus:
    description: Grant towns bonus claims or members
    usage: /townbonus <add/clear/view> <town/player>
    permission: husktowns.administrator
    aliases: [ bonus ]

permissions:
  husktowns.*:
    default: false
    description: Grant all HuskTowns Permissions
    children: [ husktowns.administrator ]
  husktowns.player:
    description: A basic pack of permissions for players
    default: false
    children:
      - husktowns.commands
      - husktowns.command.town.create
  husktowns.command.*:
    description: Grants access to all HuskTowns commands
    default: false
    children: [ husktowns.command ]
  husktowns.commands:
    description: Grants access to all HuskTowns commands
    default: false
    children:
      - husktowns.command.husktowns
      - husktowns.command.town.*
      - husktowns.command.claim
      - husktowns.command.unclaim
      - husktowns.command.claimlist
      - husktowns.command.promote
      - husktowns.command.demote
      - husktowns.command.map
      - husktowns.command.invite
      - husktowns.command.evict
      - husktowns.command.plot
      - husktowns.command.farm
      - husktowns.command.transfer
      - husktowns.command.townlist
  husktowns.administrator:
    description: Make admin claims, reload the plugin, check for updates
    default: op
    children:
      - husktowns.administrator.claim
      - husktowns.administrator.ignore_claims
      - husktowns.administrator.admin_claim_access
      - husktowns.bypass_teleport_warmup
      - husktowns.commands
      - husktowns.command.town.create
      - husktowns.town_chat_spy
      - husktowns.command.town.flag.other
      - husktowns.command.town.settings.other
  husktowns.administrator.claim:
    description: Make administrator claims
    default: op
  husktowns.administrator.ignore_claims:
    description: Toggle whether you override claim access
    default: op
  husktowns.administrator.admin_claim_access:
    description: Grants you access to building in admin claims
    default: op
  husktowns.administrator.unclaim_any:
    description: Lets you unclaim any claim in the world
    default: op
  husktowns.town_chat_spy:
    description: Spy on all town chat messages sent
    default: false
  husktowns.bypass_teleport_warmup:
    description: Lets you bypass teleportation warmup
    default: false
  husktowns.command.husktowns:
    description: Lets you use the /husktowns command
    default: true
  husktowns.command.town:
    description: Create & manage towns with /town
    default: true
    children: [ husktowns.command.town.rename ]
  husktowns.command.town.*:
    description: Lets you use all /town subcommands
    default: false
    children:
      - husktowns.command.town
      - husktowns.command.town.player
      - husktowns.command.town.rename
      - husktowns.command.town.message.bio
      - husktowns.command.town.message.greeting
      - husktowns.command.town.message.farewell
      - husktowns.command.town.settings
      - husktowns.command.town.flag.set.*
      - husktowns.command.town.spawn
      - husktowns.command.town.spawn.set
      - husktowns.command.town.spawn.privacy
      - husktowns.command.town.leave
      - husktowns.command.town.deposit
      - husktowns.command.town.help
      - husktowns.command.town.info
  husktowns.command.town.player:
    description: View info about a player
    default: true
  husktowns.command.town.help:
    description: View a list of town commands
    default: true
  husktowns.command.town.rename:
    description: Rename your town
    default: true
  husktowns.command.town.message.bio:
    description: Edit your town's bio
    default: true
  husktowns.command.town.message.greeting:
    description: Edit your town's greeting message
    default: true
  husktowns.command.town.message.farewell:
    description: Edit your town's farewell message
    default: true
  husktowns.command.town.settings:
    description: Lets you view the town settings menu
    default: true
  husktowns.command.town.settings.other:
    description: Lets you view the settings of other towns
    default: op
  husktowns.command.town.flag:
    description: Lets you modify your town flags
    default: true
  husktowns.command.town.flag.other:
    description: Lets you modify the flags of other towns
    default: op
  husktowns.command.town.flag.set.*:
    description: Lets you set all town flags
    default: false
    children:
      - husktowns.command.town.flag
      - husktowns.command.town.flag.set.explosion_damage
      - husktowns.command.town.flag.set.fire_damage
      - husktowns.command.town.flag.set.mob_griefing
      - husktowns.command.town.flag.set.monster_spawning
      - husktowns.command.town.flag.set.public_build_access
      - husktowns.command.town.flag.set.public_container_access
      - husktowns.command.town.flag.set.public_interact_access
      - husktowns.command.town.flag.set.public_farm_access
      - husktowns.command.town.flag.set.pvp
  husktowns.command.town.flag.set.explosion_damage:
    description: Lets you set the explosion damage flag
    default: true
  husktowns.command.town.flag.set.fire_damage:
    description: Lets you set the fire damage flag
    default: true
  husktowns.command.town.flag.set.mob_griefing:
    description: Lets you set the mob griefing flag
    default: true
  husktowns.command.town.flag.set.monster_spawning:
    description: Lets you set the monster spawning flag
    default: true
  husktowns.command.town.flag.set.public_build_access:
    description: Lets you set the public build access flag
    default: true
  husktowns.command.town.flag.set.public_container_access:
    description: Lets you set the public container access flag
    default: true
  husktowns.command.town.flag.set.public_interact_access:
    description: Lets you set the public interact access flag
    default: true
  husktowns.command.town.flag.set.public_farm_access:
    description: Lets you set the public farm access flag
    default: true
  husktowns.command.town.flag.set.pvp:
    description: Lets you set the pvp flag
    default: true
  husktowns.command.town.spawn:
    description: Teleport to town spawns
    default: true
  husktowns.command.town.spawn.set:
    description: Set your town's spawn position
    default: true
  husktowns.command.town.spawn.privacy:
    description: Edit the privacy of your town's spawn
    default: true
  husktowns.command.town.leave:
    description: Leave the town you are in
    default: true
  husktowns.command.town.deposit:
    description: Deposit into your town's coffers
    default: true
  husktowns.command.claim:
    description: Lets you claim chunks for your town
    default: true
  husktowns.command.unclaim:
    description: Lets you unclaim chunks
    default: true
  husktowns.command.claimlist:
    description: Lets you view a list of your town's claims
    default: true
  husktowns.command.promote:
    description: Lets you promote players in your town
    default: true
  husktowns.command.demote:
    description: Lets you demote players in your town
    default: true
  husktowns.command.map:
    description: Lets you view a map of nearby chunks
    default: true
  husktowns.command.invite:
    description: Lets you invite players to your town
    default: true
  husktowns.command.evict:
    description: Lets you evict players from your town
    default: true
  husktowns.command.farm:
    description: Lets you make claims into town farms
    default: true
  husktowns.command.plot:
    description: Lets you make and manage plots in your town
    default: true
  husktowns.command.transfer:
    description: Lets you transfer town ownership
    default: true
  husktowns.command.townlist:
    description: Lets you view a list of server towns
    default: true
  husktowns.command.town.create:
    description: Lets you make a town
    default: true
  husktowns.command.townchat:
    description: Lets you use intra-town chat
    default: true