name: Deploy Javadoc

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 16
          java-package: jdk+fx
      - name: Generate Javadoc
        run: mvn -B package --file pom.xml
      - name: Deploy Javadocs
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          clean: true
          folder: api/target/apidocs
          target_folder: apidocs
          repository-name: WiIIiam278/HuskTownsAPI